namespace Fovium.Localization;

using Fovium.Input;

internal static class UiStrings
{
    public const string MenuOpen = "menu.open";
    public const string MenuPrevious = "menu.previous";
    public const string MenuNext = "menu.next";
    public const string MenuFit = "menu.fit";
    public const string MenuActualSize = "menu.actualSize";
    public const string MenuFullscreen = "menu.fullscreen";
    public const string MenuSettings = "menu.settings";
    public const string MenuStage = "menu.stage";
    public const string MenuOverlays = "menu.overlays";
    public const string MenuClose = "menu.close";
    public const string SettingsTitle = "settings.title";
    public const string SettingsViewing = "settings.viewing";
    public const string SettingsColor = "settings.color";
    public const string SettingsAbout = "settings.about";
    public const string SettingsStage = "settings.stage";
    public const string SettingsControls = "settings.controls";
    public const string SettingsPresentation = "settings.presentation";
    public const string ColorMonitorManagement = "color.monitorManagement";
    public const string ColorUseActiveMonitorProfile = "color.useActiveMonitorProfile";
    public const string ColorMonitorManagementExplanation = "color.monitorManagementExplanation";
    public const string StageBlack = "stage.black";
    public const string StageNeutral = "stage.neutral";
    public const string StageCustom = "stage.custom";
    public const string StageAmbient = "stage.ambient";
    public const string StageBackground = "stage.background";
    public const string StageMatte = "stage.matte";
    public const string StageMatteEnabled = "stage.matteEnabled";
    public const string StageAmbientOptions = "stage.ambientOptions";
    public const string StageAmbientBrightness = "stage.ambientBrightness";
    public const string StageAmbientSaturation = "stage.ambientSaturation";
    public const string StageAmbientBlur = "stage.ambientBlur";
    public const string StageCustomColor = "stage.customColor";
    public const string StageMatteColor = "stage.matteColor";
    public const string StageMatteStyle = "stage.matteStyle";
    public const string StageMatteSize = "stage.matteSize";
    public const string StageMatteSolid = "stage.matteSolid";
    public const string StageMatteRounded = "stage.matteRounded";
    public const string StageMatteSoft = "stage.matteSoft";
    public const string StageMatteAngular = "stage.matteAngular";
    public const string ShortcutPressKey = "shortcut.pressKey";
    public const string ShortcutUnassigned = "shortcut.unassigned";
    public const string ShortcutReset = "shortcut.reset";
    public const string ShortcutConflictTitle = "shortcut.conflictTitle";
    public const string ShortcutConflictMessage = "shortcut.conflictMessage";
    public const string ShortcutInvalid = "shortcut.invalid";
    public const string CommonCancel = "common.cancel";
    public const string CommonOk = "common.ok";
    public const string ColorHex = "color.hex";
    public const string ColorInvalid = "color.invalid";
    public const string CommandPrevious = "command.previous";
    public const string CommandNext = "command.next";
    public const string CommandZoomIn = "command.zoomIn";
    public const string CommandZoomOut = "command.zoomOut";
    public const string CommandFit = "command.fit";
    public const string CommandActualSize = "command.actualSize";
    public const string CommandToggleMatte = "command.toggleMatte";
    public const string CommandFullscreen = "command.fullscreen";
    public const string CommandOpen = "command.open";
    public const string CommandSettings = "command.settings";
    public const string CommandPeek100 = "command.peek100";
    public const string CommandBlinkCompare = "command.blinkCompare";
    public const string CommandToggleHighlight = "command.toggleHighlight";
    public const string CommandToggleMarkupTools = "command.toggleMarkupTools";
    public const string CommandTogglePhotoInfo = "command.togglePhotoInfo";
    public const string CommandToggleHistogram = "command.toggleHistogram";
    public const string CommandToggleColorPicker = "command.toggleColorPicker";
    public const string CommandMarkupUndo = "command.markupUndo";
    public const string CommandMarkupRedo = "command.markupRedo";
    public const string CommandClearMarkup = "command.clearMarkup";
    public const string CommandDecreaseMarkupThickness = "command.markupThicknessDown";
    public const string CommandIncreaseMarkupThickness = "command.markupThicknessUp";
    public const string CommandDecreaseMarkupOpacity = "command.markupOpacityDown";
    public const string CommandIncreaseMarkupOpacity = "command.markupOpacityUp";
    public const string CommandDecreaseHighlightRadius = "command.highlightRadiusDown";
    public const string CommandIncreaseHighlightRadius = "command.highlightRadiusUp";
    public const string CommandSelectHandTool = "command.markupTool.hand";
    public const string CommandSelectBrushTool = "command.markupTool.brush";
    public const string CommandSelectEraserTool = "command.markupTool.eraser";
    public const string CommandSelectLineTool = "command.markupTool.line";
    public const string CommandSelectRectangleTool = "command.markupTool.rectangle";
    public const string CommandSelectEllipseTool = "command.markupTool.ellipse";
    public const string CommandSelectArrowTool = "command.markupTool.arrow";
    public const string CommandTemporaryMarkupHand = "command.markupTemporaryHand";
    public const string CommandGroupNavigation = "commandGroup.navigation";
    public const string CommandGroupViewing = "commandGroup.viewing";
    public const string CommandGroupInspection = "commandGroup.inspection";
    public const string CommandGroupPresentation = "commandGroup.presentation";
    public const string CommandGroupMarkup = "commandGroup.markup";
    public const string CommandGroupApplication = "commandGroup.application";
    public const string CommandScopeHighlightHint = "commandScope.highlightHint";
    public const string CommandScopeMarkupHint = "commandScope.markupHint";
    public const string PresentationEnableMarkup = "presentation.enableMarkup";
    public const string PresentationHighlight = "presentation.highlight";
    public const string PresentationHighlightColor = "presentation.highlightColor";
    public const string PresentationHighlightOpacity = "presentation.highlightOpacity";
    public const string PresentationHighlightRadius = "presentation.highlightRadius";
    public const string PresentationMarkupDefaults = "presentation.markupDefaults";
    public const string PresentationMarkupColor = "presentation.markupColor";
    public const string PresentationStroke = "presentation.stroke";
    public const string PresentationBrush = "presentation.brush";
    public const string PresentationEraser = "presentation.eraser";
    public const string PresentationLine = "presentation.line";
    public const string PresentationRectangle = "presentation.rectangle";
    public const string PresentationEllipse = "presentation.ellipse";
    public const string PresentationArrow = "presentation.arrow";
    public const string PresentationColor = "presentation.color";
    public const string PresentationOpacity = "presentation.opacity";
    public const string PresentationClear = "presentation.clear";
    public const string PresentationUndo = "presentation.undo";
    public const string PresentationRedo = "presentation.redo";
    public const string PresentationHand = "presentation.hand";
    public const string PresentationMovePanel = "presentation.movePanel";
    public const string PhotoInfoTitle = "photoInfo.title";
    public const string PhotoInfoClose = "photoInfo.close";
    public const string HistogramTitle = "histogram.title";
    public const string HistogramClose = "histogram.close";
    public const string ColorPickerTitle = "colorPicker.title";
    public const string ColorPickerClose = "colorPicker.close";
    public const string ColorPickerEmpty = "colorPicker.empty";
    public const string ColorPickerRecent = "colorPicker.recent";
    public const string ColorPickerTransparent = "colorPicker.transparent";
    public const string ColorPickerApproximate = "colorPicker.approximate";
    public const string ColorPickerRgb = "colorPicker.rgb";
    public const string ColorPickerRgba = "colorPicker.rgba";
    public const string SettingsScaleOnImageChange = "settings.scaleOnImageChange";
    public const string SettingsKeepCurrentScale = "settings.keepCurrentScale";
    public const string SettingsFitEachImage = "settings.fitEachImage";
    public const string SettingsVersion = "settings.version";
    public const string PickerTitle = "picker.title";
    public const string PickerImageType = "picker.imageType";
    public const string ErrorMissing = "error.missing";
    public const string ErrorUnsupported = "error.unsupported";
    public const string ErrorCorrupt = "error.corrupt";
    public const string ErrorResourceLimit = "error.resourceLimit";
    public const string ErrorDecodeFailed = "error.decodeFailed";

    public static string ForCommand(ViewerCommand command) => command switch
    {
        ViewerCommand.PreviousImage => CommandPrevious,
        ViewerCommand.NextImage => CommandNext,
        ViewerCommand.ZoomIn => CommandZoomIn,
        ViewerCommand.ZoomOut => CommandZoomOut,
        ViewerCommand.Fit => CommandFit,
        ViewerCommand.ActualSize => CommandActualSize,
        ViewerCommand.ToggleMatte => CommandToggleMatte,
        ViewerCommand.Fullscreen => CommandFullscreen,
        ViewerCommand.Open => CommandOpen,
        ViewerCommand.Settings => CommandSettings,
        ViewerCommand.Peek100 => CommandPeek100,
        ViewerCommand.BlinkCompare => CommandBlinkCompare,
        ViewerCommand.ToggleHighlight => CommandToggleHighlight,
        ViewerCommand.ToggleMarkupTools => CommandToggleMarkupTools,
        ViewerCommand.TogglePhotoInfo => CommandTogglePhotoInfo,
        ViewerCommand.ToggleHistogram => CommandToggleHistogram,
        ViewerCommand.ToggleColorPicker => CommandToggleColorPicker,
        ViewerCommand.MarkupUndo => CommandMarkupUndo,
        ViewerCommand.MarkupRedo => CommandMarkupRedo,
        ViewerCommand.ClearMarkup => CommandClearMarkup,
        ViewerCommand.DecreaseMarkupThickness => CommandDecreaseMarkupThickness,
        ViewerCommand.IncreaseMarkupThickness => CommandIncreaseMarkupThickness,
        ViewerCommand.DecreaseMarkupOpacity => CommandDecreaseMarkupOpacity,
        ViewerCommand.IncreaseMarkupOpacity => CommandIncreaseMarkupOpacity,
        ViewerCommand.DecreaseHighlightRadius => CommandDecreaseHighlightRadius,
        ViewerCommand.IncreaseHighlightRadius => CommandIncreaseHighlightRadius,
        ViewerCommand.SelectHandTool => CommandSelectHandTool,
        ViewerCommand.SelectBrushTool => CommandSelectBrushTool,
        ViewerCommand.SelectEraserTool => CommandSelectEraserTool,
        ViewerCommand.SelectLineTool => CommandSelectLineTool,
        ViewerCommand.SelectRectangleTool => CommandSelectRectangleTool,
        ViewerCommand.SelectEllipseTool => CommandSelectEllipseTool,
        ViewerCommand.SelectArrowTool => CommandSelectArrowTool,
        ViewerCommand.TemporaryMarkupHand => CommandTemporaryMarkupHand,
        _ => throw new ArgumentOutOfRangeException(nameof(command)),
    };

    public static string ForCommandGroup(ViewerCommandGroup group) => group switch
    {
        ViewerCommandGroup.Navigation => CommandGroupNavigation,
        ViewerCommandGroup.Viewing => CommandGroupViewing,
        ViewerCommandGroup.Inspection => CommandGroupInspection,
        ViewerCommandGroup.Presentation => CommandGroupPresentation,
        ViewerCommandGroup.Markup => CommandGroupMarkup,
        ViewerCommandGroup.Application => CommandGroupApplication,
        _ => throw new ArgumentOutOfRangeException(nameof(group)),
    };
}
