namespace Fovium.Localization;

using Fovium.Input;

internal static class UiStrings
{
    public const string MenuOpen = "menu.open";
    public const string MenuPrevious = "menu.previous";
    public const string MenuNext = "menu.next";
    public const string MenuFit = "menu.fit";
    public const string MenuActualSize = "menu.actualSize";
    public const string MenuFullscreen = "menu.fullscreen";
    public const string MenuSettings = "menu.settings";
    public const string MenuStage = "menu.stage";
    public const string MenuOverlays = "menu.overlays";
    public const string MenuClose = "menu.close";
    public const string SettingsTitle = "settings.title";
    public const string SettingsViewing = "settings.viewing";
    public const string SettingsColor = "settings.color";
    public const string SettingsAbout = "settings.about";
    public const string SettingsStage = "settings.stage";
    public const string SettingsControls = "settings.controls";
    public const string SettingsPresentation = "settings.presentation";
    public const string ColorMonitorManagement = "color.monitorManagement";
    public const string ColorUseActiveMonitorProfile = "color.useActiveMonitorProfile";
    public const string ColorMonitorManagementExplanation = "color.monitorManagementExplanation";
    public const string StageBlack = "stage.black";
    public const string StageNeutral = "stage.neutral";
    public const string StageCustom = "stage.custom";
    public const string StageAmbient = "stage.ambient";
    public const string StageAverage = "stage.average";
    public const string StageDominant = "stage.dominant";
    public const string StageColorWash = "stage.colorWash";
    public const string StageBackground = "stage.background";
    public const string StageMatte = "stage.matte";
    public const string StageMatteEnabled = "stage.matteEnabled";
    public const string StageAmbientOptions = "stage.ambientOptions";
    public const string StageAmbientBrightness = "stage.ambientBrightness";
    public const string StageAmbientSaturation = "stage.ambientSaturation";
    public const string StageAmbientBlur = "stage.ambientBlur";
    public const string StageCustomColor = "stage.customColor";
    public const string StageMatteColor = "stage.matteColor";
    public const string StageMatteColorSource = "stage.matteColorSource";
    public const string StagePhotoSeparation = "stage.photoSeparation";
    public const string StageSeparationNone = "stage.separationNone";
    public const string StageHairlineAuto = "stage.hairlineAuto";
    public const string StageMatteStyle = "stage.matteStyle";
    public const string StageMatteSize = "stage.matteSize";
    public const string StageMatteSolid = "stage.matteSolid";
    public const string StageMatteRounded = "stage.matteRounded";
    public const string StageMatteSoft = "stage.matteSoft";
    public const string StageMatteAngular = "stage.matteAngular";
    public const string ShortcutPressKey = "shortcut.pressKey";
    public const string ShortcutUnassigned = "shortcut.unassigned";
    public const string ShortcutReset = "shortcut.reset";
    public const string ShortcutConflictTitle = "shortcut.conflictTitle";
    public const string ShortcutConflictMessage = "shortcut.conflictMessage";
    public const string ShortcutInvalid = "shortcut.invalid";
    public const string CommonCancel = "common.cancel";
    public const string CommonOk = "common.ok";
    public const string ColorHex = "color.hex";
    public const string ColorInvalid = "color.invalid";
    public const string CommandPrevious = "command.previous";
    public const string CommandNext = "command.next";
    public const string CommandZoomIn = "command.zoomIn";
    public const string CommandZoomOut = "command.zoomOut";
    public const string CommandFit = "command.fit";
    public const string CommandActualSize = "command.actualSize";
    public const string CommandToggleSlideshow = "command.toggleSlideshow";
    public const string CommandTogglePhotoPresentation = "command.togglePhotoPresentation";
    public const string CommandToggleMatte = "command.toggleMatte";
    public const string CommandFullscreen = "command.fullscreen";
    public const string CommandOpen = "command.open";
    public const string CommandSettings = "command.settings";
    public const string CommandPeek100 = "command.peek100";
    public const string CommandBlinkCompare = "command.blinkCompare";
    public const string CommandToggleHighlight = "command.toggleHighlight";
    public const string CommandToggleMarkupTools = "command.toggleMarkupTools";
    public const string CommandTogglePhotoInfo = "command.togglePhotoInfo";
    public const string CommandToggleHistogram = "command.toggleHistogram";
    public const string CommandToggleColorPicker = "command.toggleColorPicker";
    public const string CommandMarkupUndo = "command.markupUndo";
    public const string CommandMarkupRedo = "command.markupRedo";
    public const string CommandClearMarkup = "command.clearMarkup";
    public const string CommandDecreaseMarkupThickness = "command.markupThicknessDown";
    public const string CommandIncreaseMarkupThickness = "command.markupThicknessUp";
    public const string CommandDecreaseMarkupOpacity = "command.markupOpacityDown";
    public const string CommandIncreaseMarkupOpacity = "command.markupOpacityUp";
    public const string CommandDecreaseHighlightRadius = "command.highlightRadiusDown";
    public const string CommandIncreaseHighlightRadius = "command.highlightRadiusUp";
    public const string CommandSelectHandTool = "command.markupTool.hand";
    public const string CommandSelectBrushTool = "command.markupTool.brush";
    public const string CommandSelectEraserTool = "command.markupTool.eraser";
    public const string CommandSelectLineTool = "command.markupTool.line";
    public const string CommandSelectRectangleTool = "command.markupTool.rectangle";
    public const string CommandSelectEllipseTool = "command.markupTool.ellipse";
    public const string CommandSelectArrowTool = "command.markupTool.arrow";
    public const string CommandTemporaryMarkupHand = "command.markupTemporaryHand";
    public const string CommandGroupNavigation = "commandGroup.navigation";
    public const string CommandGroupViewing = "commandGroup.viewing";
    public const string CommandGroupInspection = "commandGroup.inspection";
    public const string CommandGroupPresentation = "commandGroup.presentation";
    public const string CommandGroupMarkup = "commandGroup.markup";
    public const string CommandGroupApplication = "commandGroup.application";
    public const string CommandScopeHighlightHint = "commandScope.highlightHint";
    public const string CommandScopeMarkupHint = "commandScope.markupHint";
    public const string PresentationEnableMarkup = "presentation.enableMarkup";
    public const string PresentationHighlight = "presentation.highlight";
    public const string PresentationHighlightColor = "presentation.highlightColor";
    public const string PresentationHighlightOpacity = "presentation.highlightOpacity";
    public const string PresentationHighlightRadius = "presentation.highlightRadius";
    public const string PresentationMarkupDefaults = "presentation.markupDefaults";
    public const string PresentationMarkupColor = "presentation.markupColor";
    public const string PresentationStroke = "presentation.stroke";
    public const string PresentationBrush = "presentation.brush";
    public const string PresentationEraser = "presentation.eraser";
    public const string PresentationLine = "presentation.line";
    public const string PresentationRectangle = "presentation.rectangle";
    public const string PresentationEllipse = "presentation.ellipse";
    public const string PresentationArrow = "presentation.arrow";
    public const string PresentationColor = "presentation.color";
    public const string PresentationOpacity = "presentation.opacity";
    public const string PresentationClear = "presentation.clear";
    public const string PresentationUndo = "presentation.undo";
    public const string PresentationRedo = "presentation.redo";
    public const string PresentationHand = "presentation.hand";
    public const string PresentationMovePanel = "presentation.movePanel";
    public const string PresentationCloseMarkup = "presentation.closeMarkup";
    public const string PhotoInfoTitle = "photoInfo.title";
    public const string PhotoInfoClose = "photoInfo.close";
    public const string PhotoInfoCamera = "photoInfo.camera";
    public const string PhotoInfoLens = "photoInfo.lens";
    public const string PhotoInfoFocalLength = "photoInfo.focalLength";
    public const string PhotoInfoAperture = "photoInfo.aperture";
    public const string PhotoInfoShutter = "photoInfo.shutter";
    public const string PhotoInfoIso = "photoInfo.iso";
    public const string PhotoInfoExposureCompensation = "photoInfo.exposureCompensation";
    public const string PhotoInfoExposureMode = "photoInfo.exposureMode";
    public const string PhotoInfoMetering = "photoInfo.metering";
    public const string PhotoInfoWhiteBalance = "photoInfo.whiteBalance";
    public const string PhotoInfoFlash = "photoInfo.flash";
    public const string PhotoInfoCaptured = "photoInfo.captured";
    public const string PhotoInfoDimensions = "photoInfo.dimensions";
    public const string PhotoInfoFile = "photoInfo.file";
    public const string PhotoInfoCameraTip = "photoInfo.camera.tip";
    public const string PhotoInfoLensTip = "photoInfo.lens.tip";
    public const string PhotoInfoFocalLengthTip = "photoInfo.focalLength.tip";
    public const string PhotoInfoApertureTip = "photoInfo.aperture.tip";
    public const string PhotoInfoShutterTip = "photoInfo.shutter.tip";
    public const string PhotoInfoIsoTip = "photoInfo.iso.tip";
    public const string PhotoInfoExposureCompensationTip = "photoInfo.exposureCompensation.tip";
    public const string PhotoInfoExposureModeTip = "photoInfo.exposureMode.tip";
    public const string PhotoInfoMeteringTip = "photoInfo.metering.tip";
    public const string PhotoInfoWhiteBalanceTip = "photoInfo.whiteBalance.tip";
    public const string PhotoInfoFlashTip = "photoInfo.flash.tip";
    public const string PhotoInfoCapturedTip = "photoInfo.captured.tip";
    public const string PhotoInfoDimensionsTip = "photoInfo.dimensions.tip";
    public const string PhotoInfoFileTip = "photoInfo.file.tip";
    public const string PhotoInfoExposureModeAuto = "photoInfo.value.exposureMode.auto";
    public const string PhotoInfoExposureModeManual = "photoInfo.value.exposureMode.manual";
    public const string PhotoInfoExposureModeProgram = "photoInfo.value.exposureMode.program";

    public const string PhotoInfoExposureModeAperturePriority =
        "photoInfo.value.exposureMode.aperturePriority";

    public const string PhotoInfoExposureModeShutterPriority =
        "photoInfo.value.exposureMode.shutterPriority";

    public const string PhotoInfoExposureModeCreativeProgram =
        "photoInfo.value.exposureMode.creativeProgram";

    public const string PhotoInfoExposureModeActionProgram =
        "photoInfo.value.exposureMode.actionProgram";

    public const string PhotoInfoExposureModePortrait = "photoInfo.value.exposureMode.portrait";
    public const string PhotoInfoExposureModeLandscape = "photoInfo.value.exposureMode.landscape";
    public const string PhotoInfoExposureModeAutoBracket = "photoInfo.value.exposureMode.autoBracket";
    public const string PhotoInfoMeteringAverage = "photoInfo.value.metering.average";
    public const string PhotoInfoMeteringCenterWeighted = "photoInfo.value.metering.centerWeighted";
    public const string PhotoInfoMeteringSpot = "photoInfo.value.metering.spot";
    public const string PhotoInfoMeteringMultiSpot = "photoInfo.value.metering.multiSpot";
    public const string PhotoInfoMeteringMatrix = "photoInfo.value.metering.matrix";
    public const string PhotoInfoMeteringPartial = "photoInfo.value.metering.partial";
    public const string PhotoInfoMeteringOther = "photoInfo.value.metering.other";
    public const string PhotoInfoWhiteBalanceAuto = "photoInfo.value.whiteBalance.auto";
    public const string PhotoInfoWhiteBalanceManual = "photoInfo.value.whiteBalance.manual";
    public const string PhotoInfoFlashDidNotFire = "photoInfo.value.flash.didNotFire";
    public const string PhotoInfoFlashFired = "photoInfo.value.flash.fired";
    public const string HistogramTitle = "histogram.title";
    public const string HistogramClose = "histogram.close";
    public const string ColorPickerTitle = "colorPicker.title";
    public const string ColorPickerClose = "colorPicker.close";
    public const string ColorPickerEmpty = "colorPicker.empty";
    public const string ColorPickerRecent = "colorPicker.recent";
    public const string ColorPickerTransparent = "colorPicker.transparent";
    public const string ColorPickerApproximate = "colorPicker.approximate";
    public const string ColorPickerRgb = "colorPicker.rgb";
    public const string ColorPickerRgba = "colorPicker.rgba";
    public const string ColorPickerClear = "colorPicker.clear";
    public const string ColorPickerDetailHex = "colorPicker.detail.hex";
    public const string ColorPickerDetailRgb = "colorPicker.detail.rgb";
    public const string ColorPickerDetailRgba = "colorPicker.detail.rgba";
    public const string ColorPickerDetailOklch = "colorPicker.detail.oklch";
    public const string ColorPickerDetailHue = "colorPicker.detail.hue";
    public const string ColorPickerDetailUndertone = "colorPicker.detail.undertone";
    public const string ColorPickerDetailLightness = "colorPicker.detail.lightness";
    public const string ColorPickerDetailChroma = "colorPicker.detail.chroma";
    public const string ColorPickerDetailCreativeName = "colorPicker.detail.creativeName";
    public const string ColorPickerNameBlack = "colorPicker.name.black";
    public const string ColorPickerNameDarkGray = "colorPicker.name.darkGray";
    public const string ColorPickerNameGray = "colorPicker.name.gray";
    public const string ColorPickerNameLightGray = "colorPicker.name.lightGray";
    public const string ColorPickerNameWhite = "colorPicker.name.white";
    public const string ColorPickerHueNeutral = "colorPicker.hue.neutral";
    public const string ColorPickerHueWarmGray = "colorPicker.hue.warmGray";
    public const string ColorPickerHueCoolGray = "colorPicker.hue.coolGray";
    public const string ColorPickerHueBlueGray = "colorPicker.hue.blueGray";
    public const string ColorPickerHueGreenGray = "colorPicker.hue.greenGray";
    public const string ColorPickerHueOliveGray = "colorPicker.hue.oliveGray";
    public const string ColorPickerHueRoseGray = "colorPicker.hue.roseGray";
    public const string ColorPickerHueVioletGray = "colorPicker.hue.violetGray";
    public const string ColorPickerHueLilacGray = "colorPicker.hue.lilacGray";
    public const string ColorPickerHueGreige = "colorPicker.hue.greige";
    public const string ColorPickerHueBeige = "colorPicker.hue.beige";
    public const string ColorPickerHueSand = "colorPicker.hue.sand";
    public const string ColorPickerHueCream = "colorPicker.hue.cream";
    public const string ColorPickerHuePeach = "colorPicker.hue.peach";
    public const string ColorPickerHueApricot = "colorPicker.hue.apricot";
    public const string ColorPickerHueOchre = "colorPicker.hue.ochre";
    public const string ColorPickerHueMustard = "colorPicker.hue.mustard";
    public const string ColorPickerHueTaupe = "colorPicker.hue.taupe";
    public const string ColorPickerHueTerracotta = "colorPicker.hue.terracotta";
    public const string ColorPickerHueRed = "colorPicker.hue.red";
    public const string ColorPickerHueRedOrange = "colorPicker.hue.redOrange";
    public const string ColorPickerHueCoral = "colorPicker.hue.coral";
    public const string ColorPickerHueOrange = "colorPicker.hue.orange";
    public const string ColorPickerHueAmber = "colorPicker.hue.amber";
    public const string ColorPickerHueYellow = "colorPicker.hue.yellow";
    public const string ColorPickerHueYellowGreen = "colorPicker.hue.yellowGreen";
    public const string ColorPickerHueOliveGreen = "colorPicker.hue.oliveGreen";
    public const string ColorPickerHueGreen = "colorPicker.hue.green";
    public const string ColorPickerHueTurquoise = "colorPicker.hue.turquoise";
    public const string ColorPickerHueTurquoiseCyan = "colorPicker.hue.turquoiseCyan";
    public const string ColorPickerHueCyan = "colorPicker.hue.cyan";
    public const string ColorPickerHueCyanBlue = "colorPicker.hue.cyanBlue";
    public const string ColorPickerHueBlue = "colorPicker.hue.blue";
    public const string ColorPickerHueBlueViolet = "colorPicker.hue.blueViolet";
    public const string ColorPickerHueViolet = "colorPicker.hue.violet";
    public const string ColorPickerHuePinkLilac = "colorPicker.hue.pinkLilac";
    public const string ColorPickerHueMagenta = "colorPicker.hue.magenta";
    public const string ColorPickerHueRedMagenta = "colorPicker.hue.redMagenta";
    public const string ColorPickerHuePink = "colorPicker.hue.pink";
    public const string ColorPickerHueRose = "colorPicker.hue.rose";
    public const string ColorPickerHueCrimson = "colorPicker.hue.crimson";
    public const string ColorPickerHueBurgundy = "colorPicker.hue.burgundy";
    public const string ColorPickerHueBrown = "colorPicker.hue.brown";
    public const string ColorPickerHueOlive = "colorPicker.hue.olive";
    public const string ColorPickerNameRedBlack = "colorPicker.name.redBlack";
    public const string ColorPickerNameBrownBlack = "colorPicker.name.brownBlack";
    public const string ColorPickerNameOliveBlack = "colorPicker.name.oliveBlack";
    public const string ColorPickerNameGreenBlack = "colorPicker.name.greenBlack";
    public const string ColorPickerNameCyanBlack = "colorPicker.name.cyanBlack";
    public const string ColorPickerNameBlueBlack = "colorPicker.name.blueBlack";
    public const string ColorPickerNameVioletBlack = "colorPicker.name.violetBlack";
    public const string ColorPickerNameRoseBlack = "colorPicker.name.roseBlack";
    public const string ColorPickerNameRedWhite = "colorPicker.name.redWhite";
    public const string ColorPickerNameCreamWhite = "colorPicker.name.creamWhite";
    public const string ColorPickerNameGreenWhite = "colorPicker.name.greenWhite";
    public const string ColorPickerNameCyanWhite = "colorPicker.name.cyanWhite";
    public const string ColorPickerNameBlueWhite = "colorPicker.name.blueWhite";
    public const string ColorPickerNameVioletWhite = "colorPicker.name.violetWhite";
    public const string ColorPickerNamePinkWhite = "colorPicker.name.pinkWhite";
    public const string ColorPickerUndertoneWarm = "colorPicker.undertone.warm";
    public const string ColorPickerUndertoneCool = "colorPicker.undertone.cool";
    public const string ColorPickerUndertoneLilac = "colorPicker.undertone.lilac";
    public const string ColorPickerLightnessVeryDark = "colorPicker.lightness.veryDark";
    public const string ColorPickerLightnessDark = "colorPicker.lightness.dark";
    public const string ColorPickerLightnessMedium = "colorPicker.lightness.medium";
    public const string ColorPickerLightnessLight = "colorPicker.lightness.light";
    public const string ColorPickerLightnessVeryLight = "colorPicker.lightness.veryLight";
    public const string ColorPickerChromaNeutral = "colorPicker.chroma.neutral";
    public const string ColorPickerChromaMuted = "colorPicker.chroma.muted";
    public const string ColorPickerChromaModerate = "colorPicker.chroma.moderate";
    public const string ColorPickerChromaSaturated = "colorPicker.chroma.saturated";
    public const string ColorPickerChromaVivid = "colorPicker.chroma.vivid";
    public const string ColorPickerModifierVeryDark = "colorPicker.modifier.veryDark";
    public const string ColorPickerModifierDark = "colorPicker.modifier.dark";
    public const string ColorPickerModifierMedium = "colorPicker.modifier.medium";
    public const string ColorPickerModifierLight = "colorPicker.modifier.light";
    public const string ColorPickerModifierVeryLight = "colorPicker.modifier.veryLight";
    public const string ColorPickerModifierNeutral = "colorPicker.modifier.neutral";
    public const string ColorPickerModifierMuted = "colorPicker.modifier.muted";
    public const string ColorPickerModifierModerate = "colorPicker.modifier.moderate";
    public const string ColorPickerModifierSaturated = "colorPicker.modifier.saturated";
    public const string ColorPickerModifierVivid = "colorPicker.modifier.vivid";

    public const string ColorPickerNameLightnessChromaHue =
        "colorPicker.name.lightnessChromaHue";

    public const string ColorPickerNameLightnessHue = "colorPicker.name.lightnessHue";
    public const string ColorPickerNameChromaHue = "colorPicker.name.chromaHue";
    public const string SettingsScaleOnImageChange = "settings.scaleOnImageChange";
    public const string SettingsKeepCurrentScale = "settings.keepCurrentScale";
    public const string SettingsFitEachImage = "settings.fitEachImage";
    public const string SettingsPhotoPresentationView = "settings.photoPresentationView";

    public const string SettingsEnablePhotoPresentation =
        "settings.enablePhotoPresentation";

    public const string SettingsPhotoPresentationEdgeMargin =
        "settings.photoPresentationEdgeMargin";

    public const string SettingsPhotoPresentationExplanation =
        "settings.photoPresentationExplanation";

    public const string Slideshow = "slideshow.title";
    public const string SlideshowStart = "slideshow.start";
    public const string SlideshowStop = "slideshow.stop";
    public const string SlideshowSlideDuration = "slideshow.slideDuration";
    public const string SlideshowSeconds = "slideshow.seconds";
    public const string SlideshowAtEnd = "slideshow.atEnd";
    public const string SlideshowStopOnLast = "slideshow.stopOnLast";
    public const string SlideshowStartAgain = "slideshow.startAgain";
    public const string SettingsVersion = "settings.version";
    public const string PickerTitle = "picker.title";
    public const string PickerImageType = "picker.imageType";
    public const string ErrorMissing = "error.missing";
    public const string ErrorUnsupported = "error.unsupported";
    public const string ErrorCorrupt = "error.corrupt";
    public const string ErrorResourceLimit = "error.resourceLimit";
    public const string ErrorDecodeFailed = "error.decodeFailed";

    public static string ForCommand(ViewerCommand command) => command switch
    {
        ViewerCommand.PreviousImage => CommandPrevious,
        ViewerCommand.NextImage => CommandNext,
        ViewerCommand.ZoomIn => CommandZoomIn,
        ViewerCommand.ZoomOut => CommandZoomOut,
        ViewerCommand.Fit => CommandFit,
        ViewerCommand.ActualSize => CommandActualSize,
        ViewerCommand.ToggleSlideshow => CommandToggleSlideshow,
        ViewerCommand.TogglePhotoPresentation => CommandTogglePhotoPresentation,
        ViewerCommand.ToggleMatte => CommandToggleMatte,
        ViewerCommand.Fullscreen => CommandFullscreen,
        ViewerCommand.Open => CommandOpen,
        ViewerCommand.Settings => CommandSettings,
        ViewerCommand.Peek100 => CommandPeek100,
        ViewerCommand.BlinkCompare => CommandBlinkCompare,
        ViewerCommand.ToggleHighlight => CommandToggleHighlight,
        ViewerCommand.ToggleMarkupTools => CommandToggleMarkupTools,
        ViewerCommand.TogglePhotoInfo => CommandTogglePhotoInfo,
        ViewerCommand.ToggleHistogram => CommandToggleHistogram,
        ViewerCommand.ToggleColorPicker => CommandToggleColorPicker,
        ViewerCommand.MarkupUndo => CommandMarkupUndo,
        ViewerCommand.MarkupRedo => CommandMarkupRedo,
        ViewerCommand.ClearMarkup => CommandClearMarkup,
        ViewerCommand.DecreaseMarkupThickness => CommandDecreaseMarkupThickness,
        ViewerCommand.IncreaseMarkupThickness => CommandIncreaseMarkupThickness,
        ViewerCommand.DecreaseMarkupOpacity => CommandDecreaseMarkupOpacity,
        ViewerCommand.IncreaseMarkupOpacity => CommandIncreaseMarkupOpacity,
        ViewerCommand.DecreaseHighlightRadius => CommandDecreaseHighlightRadius,
        ViewerCommand.IncreaseHighlightRadius => CommandIncreaseHighlightRadius,
        ViewerCommand.SelectHandTool => CommandSelectHandTool,
        ViewerCommand.SelectBrushTool => CommandSelectBrushTool,
        ViewerCommand.SelectEraserTool => CommandSelectEraserTool,
        ViewerCommand.SelectLineTool => CommandSelectLineTool,
        ViewerCommand.SelectRectangleTool => CommandSelectRectangleTool,
        ViewerCommand.SelectEllipseTool => CommandSelectEllipseTool,
        ViewerCommand.SelectArrowTool => CommandSelectArrowTool,
        ViewerCommand.TemporaryMarkupHand => CommandTemporaryMarkupHand,
        _ => throw new ArgumentOutOfRangeException(nameof(command)),
    };

    public static string ForCommandGroup(ViewerCommandGroup group) => group switch
    {
        ViewerCommandGroup.Navigation => CommandGroupNavigation,
        ViewerCommandGroup.Viewing => CommandGroupViewing,
        ViewerCommandGroup.Inspection => CommandGroupInspection,
        ViewerCommandGroup.Presentation => CommandGroupPresentation,
        ViewerCommandGroup.Markup => CommandGroupMarkup,
        ViewerCommandGroup.Application => CommandGroupApplication,
        _ => throw new ArgumentOutOfRangeException(nameof(group)),
    };
}